/**
 * Copyright 2021 Wultra s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// PA2_SHARED_SOURCE PowerAuth2ForWatch .

// Do not edit this file in PowerAuth2ForWatch project. Use version in
// PowerAuht2ForExtensions and the shared file will be copied in the next
// copy-shared-sources.sh run.

#import "PowerAuthMacros.h"

/** Class representing a multi-factor authentication object.
 */
@interface PowerAuthAuthentication : NSObject

/// No longer available. Use static methods instead.
- (nonnull instancetype) init NS_UNAVAILABLE;

/// Indicates if a possession factor should be used.
@property (nonatomic, assign, readonly) BOOL usePossession;

/// Indicates if a biometry factor should be used.
@property (nonatomic, assign, readonly) BOOL useBiometry;

/// Contains password in case that knowledge factor is required in authentication.
@property (nonatomic, strong, readonly, nullable) NSString * password;

@end

@interface PowerAuthAuthentication (EasyAccessors)

// Signing, Possession only

/// Create a new instance of authentication object preconfigured for signing with a possession factor.
/// @return Instance of PowerAuthAuthentication configured for signing with a possession factor.
+ (nonnull PowerAuthAuthentication *) possession;

@end
